### ISSUE TITLE
ORForise.Annotation_Compare failing after a few matches

### ISSUE THREAD

**Issue by Naughtoncolin** [NickJD/ORForise#1]
ORForise.Annotation_Compare seems to be having an issue after matching a few genes. Running the command: 

`python3 -m ORForise.Annotation_Compare -dna ../reference/Listeria_ref.fasta \
-ref ../reference/Listeria_geneAnnotations.gff3 \
-t Prodigal -tp ../prodigal_output_tool/prodigal_gffCGT1005_contigs.gff \
-v True`

gives the output:

No Hit
Out of Frame Predicted CDS
Out of Frame Predicted CDS
Partial Match
Traceback (most recent call last):
  File "/home/groupc/anaconda3/envs/team3_gene_prediction/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/groupc/anaconda3/envs/team3_gene_prediction/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/groupc/anaconda3/envs/team3_gene_prediction/lib/python3.10/site-packages/ORForise/Annotation_Compare.py", line 167, in <module>
    comparator(**vars(args))
  File "/home/groupc/anaconda3/envs/team3_gene_prediction/lib/python3.10/site-packages/ORForise/Annotation_Compare.py", line 80, in comparator
    all_Metrics, all_rep_Metrics, start_precision, stop_precision, other_starts, other_stops, perfect_Matches, missed_genes, unmatched_orfs, undetected_gene_metrics, unmatched_orf_metrics, orf_Coverage_Genome, matched_ORF_Coverage_Genome, gene_coverage_genome, multi_Matched_ORFs, partial_Hits = tool_comparison(
  File "/home/groupc/anaconda3/envs/team3_gene_prediction/lib/python3.10/site-packages/ORForise/Comparator.py", line 332, in tool_comparison
    previously_Covered_Gene = comp.matched_ORFs[g_pos][-1]
KeyError: '4869,5981'

Can you please advise on this?

**Comment by NickJD** [comment]
Hi - Thanks for reporting this.
I think the issue is that the reference GFF file may contain two CDS genes with the same start position but a different stop position -This causes issues with how I handle the order of ref CDS's.
This problem came up before and I made a fix to the version on Github but not on pip.
I have just pushed that fix to pip so please update your version from there and let me know if it works - Should be: _pip install ORForise --upgrade_
If not, please can you send me the input files you are using. **Email - nicholas@dimonaco.co.uk.**

Thanks.
