### ISSUE TITLE
Division by zero error when running Annotation_Compare on GeneMarkS gff

### ISSUE THREAD

**Issue by Naughtoncolin** [NickJD/ORForise#2]
I'm having a problem analyzing a gff made with GeneMarksS. Running the following command:

 `python3 -m ORForise.Annotation_Compare \
-dna ../reference/Listeria_monocytogenes_serotype_4b_str_ll195_gca_000318055.ASM31805v1.dna.chromosome.Chromosome.fa \
-ref ../reference/Listeria_monocytogenes_serotype_4b_str_ll195_gca_000318055.ASM31805v1.52.chromosome.Chromosome.gff3 \
-t Prodigal \
-tp ../genemarks_out/CGT1029_contigs_genemarks_out.gff `

throws the following error:

Traceback (most recent call last):
  File "/home/groupc/analysis/Team3-GenePrediction/sandbox/../sandbox/ORForise/src/ORForise/Annotation_Compare.py", line 173, in <module>
    comparator(**vars(args))
  File "/home/groupc/analysis/Team3-GenePrediction/sandbox/../sandbox/ORForise/src/ORForise/Annotation_Compare.py", line 85, in comparator
    orfs = tool_(tool_prediction, genome_Seq)
  File "/home/groupc/analysis/Team3-GenePrediction/sandbox/ORForise/src/ORForise/Tools/Prodigal/Prodigal.py", line 18, in Prodigal
    if "Prodigal" in line[1] and "CDS" in line[2]:
IndexError: list index out of range
(base) [cnaughton7@biogenome2022 sandbox]$ less ../genemarks_out/CGT1029_contigs_genemarks_out.gff 
(base) [cnaughton7@biogenome2022 sandbox]$ python3 ../sandbox/ORForise/src/ORForise/Annotation_Compare.py -dna ../reference/Listeria_monocytogenes_serotype_4b_str_ll195_gca_000318055.ASM31805v1.dna.chromosome.Chromosome.fa -ref ../reference/Listeria_monocytogenes_serotype_4b_str_ll195_gca_000318055.ASM31805v1.52.chromosome.Chromosome.gff3 -t GeneMark_S -tp ../genemarks_out/CGT1029_contigs_genemarks_out.gff
Traceback (most recent call last):
  File "/home/groupc/analysis/Team3-GenePrediction/sandbox/../sandbox/ORForise/src/ORForise/Annotation_Compare.py", line 173, in <module>
    comparator(**vars(args))
  File "/home/groupc/analysis/Team3-GenePrediction/sandbox/../sandbox/ORForise/src/ORForise/Annotation_Compare.py", line 86, in comparator
    all_Metrics, all_rep_Metrics, start_precision, stop_precision, other_starts, other_stops, perfect_Matches, missed_genes, unmatched_orfs, undetected_gene_metrics, unmatched_orf_metrics, orf_Coverage_Genome, matched_ORF_Coverage_Genome, gene_coverage_genome, multi_Matched_ORFs, partial_Hits = tool_comparison(
  File "/home/groupc/analysis/Team3-GenePrediction/sandbox/ORForise/src/ORForise/Comparator.py", line 389, in tool_comparison
    atg_P, gtg_P, ttg_P, att_P, ctg_P, other_Start_P, other_Starts = start_Codon_Count(orfs)
  File "/home/groupc/analysis/Team3-GenePrediction/sandbox/ORForise/src/ORForise/Comparator.py", line 177, in start_Codon_Count
    atg_P = format(100 * atg / len(orfs), '.2f')
ZeroDivisionError: division by zero

I've checked the gff and confirmed there are genes in the file. Do you see anything obvious that I'm doing wrong?

**Comment by Naughtoncolin** [comment]
There ended up being an issue with the gff file format. Apologies for opening the issue!

**Comment by NickJD** [comment]
No worries - It forced me to issue a new pip release so all good.

**Comment by NickJD** [comment]
'-t GeneMarkS' (if you are in fact using the older GeneMarkS and not GeneMarkS2) would fix it I think.
Glad you figured it out though.
